{% set name = "flippyr" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_rev: {{ version }}
  git_url: https://github.com/BEFH/flippyr.git

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - pyfaidx
    - pandas

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} setup.py install --single-version-externally-managed --record=record.txt"
  entry_points:
    - flippyr = flippyr:main

about:
  home: https://github.com/BEFH/flippyr
