package:
  name: "flippyr"
  version: "0.4.0"

source:
  git_rev: 0.4.0
  git_url: https://github.com/BEFH/flippyr.git

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - pyfaidx
    - pandas

build:
  entry_points:
    - flippyr = flippyr:main

test:
  imports:
    -

about:
  home: https://github.com/BEFH/flippyr
