name: publish_conda

on:
  release:
    types: [published]
    tags:
      - '**'

jobs:
  publish:
    name: Publish package to anaconda
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Publish Anaconda package to Anaconda.org
      uses: BEFH/anaconda-publish@v1.5.1
      with:
        subDir: 'conda_build'
        channels: 'conda-forge -c bioconda'
        AnacondaToken: ${{ secrets.ANACONDA_TOKEN }}
        publish: true
        test_all: true
        convert_win: false
        convert_osx: false
